version: '3.8'

services:
  web:
    build: ./back
    image: reapib
    container_name: reapib
    restart: unless-stopped
    env_file:
      - back/.env
    volumes:
      - ./back:/usr/src/app
    networks:
      - app-net

  front:
    build: ./front
    image: reapif
    container_name: reapif
    restart: unless-stopped
    volumes:
      - ./front:/usr/src/app
    ports:
      - "8101:5173"
    networks:
      - app-net
  
  nginx:
    build: ./nginx
    image: reapin
    container_name: reapin
    restart: unless-stopped
    ports:
      - "8102:80"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

# dr rm -f reapib && dr rm -f reapif && dr rm -f reapin
# dr image rm reapib && dr image rm reapif && dr image rm reapin
# dr network rm reapi_app-net
# drcu -d